version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: cb_container
    restart: always
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot!
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # Weaviate Vector database
  weaviate:
    #image: semitechnologies/weaviate:latest
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    container_name: weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    restart: always
    depends_on:
      weaviate-vectorizer:
        condition: service_started
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      RAFT_ENABLE_ONE_NODE_RECOVERY: 'true'
      QUERY_DEFAULTS_LIMIT: 100
      ENABLE_API_BASED_MODULES: 'true'
      #DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      #ENABLE_MODULES: text2vec-transformers
      #TRANSFORMERS_INFERENCE_API: http://weaviate-vectorizer:8080
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      #CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - backend
  #weaviate-vectorizer:
  #  image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
  #  environment:
  #    ENABLE_CUDA: 0  # set to 1 to enable if you have a GPU available for optimum performance

  # Ollama - local Llama 2/3, Mistral, Gemma
  ollama:
    image: ollama/ollama
    container_name: ollama_ai
    restart: always
    ports:
      - "11434:11434"
    networks:
      - backend
    volumes:
      - ollama_data:/root/.ollama

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    restart: always

volumes:
  postgres_data:
  weaviate_data:
  ollama_data:

networks:
  backend:
    driver: bridge

